Port color_source to React
stream-labs/desktop pull request #3916
Opened 2021-11-30 23:47 UTC by holiber

2021-12-01 21:29 UTC, trevorrl commented
the color picker input in this port is suffering from the same regression as what affects Andy's filter rework, but I'd consider it a blocker for this since it's the core functionality of the source that is being ported.

2022-02-01 20:35 UTC, andycreeth requested changes

2022-02-01 20:36 UTC, andycreeth commented on app/components-react/windows/SourceProperties.tsx
> +  const [properties, setProperties] = useState(source ? source.getPropertiesFormData() : []);
Docs here: https://reactjs.org/docs/hooks-reference.html#lazy-initial-state

2022-02-01 22:19 UTC, holiber commented on app/components-react/windows/SourceProperties.tsx
> +  const [properties, setProperties] = useState(source ? source.getPropertiesFormData() : []);
This is already fixed. This branch is not synced with fixes yet.

2022-02-11 18:31 UTC, merged