Port StudioFooter to React
stream-labs/desktop pull request #4081
Opened 2022-03-29 18:48 UTC by gettinToasty

2022-03-30 15:55 UTC, andycreeth requested changes

2022-03-30 16:49 UTC, gettinToasty commented on app/components-react/root/StudioFooter.tsx
> +  useRenderInterval(
yea this was a leftover from the old port, was thinking about that myself and i think we'll be able to get away with just using a normal interval here

2022-03-30 16:50 UTC, gettinToasty commented on app/components-react/root/StudioFooter.tsx
> +  useRenderInterval(
react 18 fixes that concern too :) so we won't have to think so hard about it

2022-03-31 16:19 UTC, andycreeth approved these changes

2022-04-12 21:30 UTC, merged