Center main page transition loader.
stream-labs/desktop pull request #4345
Opened 2022-10-28 18:12 UTC by michelinewu

2022-11-10 21:45 UTC, gettinToasty requested changes
the spinner looks extremely small when navigating to a BrowserView with these changes for some reason

2022-11-14 18:07 UTC, michelinewu commented
Should it match the size of the loader when the app is starting?
![large-loader](https://user-images.githubusercontent.com/69046953/201733705-4a73b5b1-f4cb-4724-8ccc-a8db2ae3afc1.png)

2022-11-15 18:26 UTC, michelinewu commented
Preview: ![large-loader](https://user-images.githubusercontent.com/69046953/201997323-36e37fe2-5c65-4ccf-8cfc-2c83e92614bd.png)

2022-11-15 18:28 UTC, gettinToasty approved these changes

2023-01-04 19:58 UTC, merged