Resolve spin wheel button not showing up on mini feed when widget is added to scene
stream-labs/desktop pull request #4419
Opened 2023-01-03 13:07 UTC by dec0y

2023-01-03 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stream-labs/desktop?pullRequest=4419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stream-labs/desktop?pullRequest=4419) before we can accept your contribution.<br/><hr/>**Thom Swann** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stream-labs/desktop?pullRequest=4419) it.</sub>

2023-01-03 13:07 UTC, dec0y commented
https://app.asana.com/0/734380881425048/1202485348976624/f

2023-01-03 15:10 UTC, michelinewu approved these changes

2023-01-03 16:07 UTC, gettinToasty requested changes
this fix is good if it works, but just to comply with modern code patterns i think it'd be nice if we can move it to `WidgetServiceViews`: generally speaking that's where we want to put things that read our state going forward

2023-01-03 16:10 UTC, dec0y commented
I can totally make that change and get that moved over to the new service. Totally makes sense if we're using that moving forward.

2023-01-06 23:42 UTC, gettinToasty approved these changes

2023-01-18 21:05 UTC, merged