Crash binaries identification
stream-labs/desktop pull request #4786
Opened 2023-11-15 18:31 UTC by avoitenko-logitech

2024-01-04 00:20 UTC, gettinToasty commented
/AzurePipelines run

2024-01-04 00:21 UTC, gettinToasty requested changes
This looks good, but should be based against staging

2024-01-11 14:41 UTC, avoitenko-logitech commented
Rebased on Staging

2024-01-11 15:34 UTC, avoitenko-logitech commented
`media-backup` test is failing which is not related to my changes.

2024-01-16 23:33 UTC, gettinToasty approved these changes

2024-01-16 23:34 UTC, merged